targets:
  $default:
    builders:
      # Currency code generator
      expense_tracker|currency_code:
        enabled: true
        generate_for:
          - lib/core/models/currency_code.dart

builders:
  currency_code:
    import: "package:expense_tracker/generators/currency_code_generator.dart"
    builder_factories: ["currencyCodeBuilder"]
    build_extensions: {".dart": ["_generated.dart"]}
    auto_apply: dependents
    build_to: source
