// Mocks generated by Mockito 5.4.6 from annotations
// in expense_tracker/test/core/services/activity_logger_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'package:expense_tracker/core/models/currency_code.dart' as _i12;

import 'package:expense_tracker/features/trips/domain/models/activity_log.dart'
    as _i5;
import 'package:expense_tracker/features/trips/domain/models/trip.dart' as _i2;
import 'package:expense_tracker/features/trips/domain/models/verified_member.dart'
    as _i8;
import 'package:expense_tracker/features/trips/domain/repositories/activity_log_repository.dart'
    as _i3;
import 'package:expense_tracker/features/trips/domain/repositories/trip_repository.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTrip_0 extends _i1.SmartFake implements _i2.Trip {
  _FakeTrip_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ActivityLogRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockActivityLogRepository extends _i1.Mock
    implements _i3.ActivityLogRepository {
  MockActivityLogRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> addLog(_i5.ActivityLog? log) =>
      (super.noSuchMethod(
            Invocation.method(#addLog, [log]),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(this, Invocation.method(#addLog, [log])),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Stream<List<_i5.ActivityLog>> getActivityLogs(
    String? tripId, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getActivityLogs, [tripId], {#limit: limit}),
            returnValue: _i4.Stream<List<_i5.ActivityLog>>.empty(),
          )
          as _i4.Stream<List<_i5.ActivityLog>>);
}

/// A class which mocks [TripRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTripRepository extends _i1.Mock implements _i7.TripRepository {
  MockTripRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Trip> createTrip(_i2.Trip? trip) =>
      (super.noSuchMethod(
            Invocation.method(#createTrip, [trip]),
            returnValue: _i4.Future<_i2.Trip>.value(
              _FakeTrip_0(this, Invocation.method(#createTrip, [trip])),
            ),
          )
          as _i4.Future<_i2.Trip>);

  @override
  _i4.Future<_i2.Trip?> getTripById(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#getTripById, [tripId]),
            returnValue: _i4.Future<_i2.Trip?>.value(),
          )
          as _i4.Future<_i2.Trip?>);

  @override
  _i4.Stream<List<_i2.Trip>> getAllTrips() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTrips, []),
            returnValue: _i4.Stream<List<_i2.Trip>>.empty(),
          )
          as _i4.Stream<List<_i2.Trip>>);

  @override
  _i4.Future<_i2.Trip> updateTrip(_i2.Trip? trip) =>
      (super.noSuchMethod(
            Invocation.method(#updateTrip, [trip]),
            returnValue: _i4.Future<_i2.Trip>.value(
              _FakeTrip_0(this, Invocation.method(#updateTrip, [trip])),
            ),
          )
          as _i4.Future<_i2.Trip>);

  @override
  _i4.Future<void> deleteTrip(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTrip, [tripId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> tripExists(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#tripExists, [tripId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> addVerifiedMember({
    required String tripId,
    required String? participantId,
    required String? participantName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addVerifiedMember, [], {
              #tripId: tripId,
              #participantId: participantId,
              #participantName: participantName,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i8.VerifiedMember>> getVerifiedMembers(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#getVerifiedMembers, [tripId]),
            returnValue: _i4.Future<List<_i8.VerifiedMember>>.value(
              <_i8.VerifiedMember>[],
            ),
          )
          as _i4.Future<List<_i8.VerifiedMember>>);

  @override
  _i4.Future<void> removeVerifiedMember({
    required String tripId,
    required String? participantId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeVerifiedMember, [], {
              #tripId: tripId,
              #participantId: participantId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<dynamic>> getAllowedCurrencies(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#getAllowedCurrencies, [tripId]),
            returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i4.Future<List<dynamic>>);

  @override
  _i4.Future<void> updateAllowedCurrencies(
    String tripId,
    List<_i12.CurrencyCode> currencies,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAllowedCurrencies, [tripId, currencies]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
