// Mocks generated by Mockito 5.4.6 from annotations
// in expense_tracker/test/widget/features/expenses/expense_form_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:expense_tracker/core/models/category_customization.dart'
    as _i20;
import 'package:expense_tracker/core/models/participant.dart' as _i12;
import 'package:expense_tracker/features/categories/domain/models/category.dart'
    as _i18;
import 'package:expense_tracker/features/categories/presentation/cubit/category_cubit.dart'
    as _i17;
import 'package:expense_tracker/features/categories/presentation/cubit/category_customization_cubit.dart'
    as _i19;
import 'package:expense_tracker/features/categories/presentation/cubit/category_customization_state.dart'
    as _i5;
import 'package:expense_tracker/features/categories/presentation/cubit/category_state.dart'
    as _i4;
import 'package:expense_tracker/features/expenses/domain/models/expense.dart'
    as _i7;
import 'package:expense_tracker/features/expenses/presentation/cubits/expense_cubit.dart'
    as _i6;
import 'package:expense_tracker/features/expenses/presentation/cubits/expense_state.dart'
    as _i2;
import 'package:expense_tracker/features/trips/domain/models/activity_log.dart'
    as _i13;
import 'package:expense_tracker/features/trips/domain/models/trip.dart' as _i11;
import 'package:expense_tracker/features/trips/domain/models/trip_recovery_code.dart'
    as _i15;
import 'package:expense_tracker/features/trips/domain/models/verified_member.dart'
    as _i16;
import 'package:expense_tracker/features/trips/presentation/cubits/trip_cubit.dart'
    as _i10;
import 'package:expense_tracker/features/trips/presentation/cubits/trip_state.dart'
    as _i3;
import 'package:flutter_bloc/flutter_bloc.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeExpenseState_0 extends _i1.SmartFake implements _i2.ExpenseState {
  _FakeExpenseState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTripState_1 extends _i1.SmartFake implements _i3.TripState {
  _FakeTripState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoryState_2 extends _i1.SmartFake implements _i4.CategoryState {
  _FakeCategoryState_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoryCustomizationState_3 extends _i1.SmartFake
    implements _i5.CategoryCustomizationState {
  _FakeCategoryCustomizationState_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ExpenseCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpenseCubit extends _i1.Mock implements _i6.ExpenseCubit {
  MockExpenseCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i7.Expense> get expenses =>
      (super.noSuchMethod(
            Invocation.getter(#expenses),
            returnValue: <_i7.Expense>[],
          )
          as List<_i7.Expense>);

  @override
  _i2.ExpenseState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeExpenseState_0(this, Invocation.getter(#state)),
          )
          as _i2.ExpenseState);

  @override
  _i8.Stream<_i2.ExpenseState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i8.Stream<_i2.ExpenseState>.empty(),
          )
          as _i8.Stream<_i2.ExpenseState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i8.Future<void> loadExpenses(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#loadExpenses, [tripId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> createExpense(_i7.Expense? expense, {String? actorName}) =>
      (super.noSuchMethod(
            Invocation.method(
              #createExpense,
              [expense],
              {#actorName: actorName},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateExpense(_i7.Expense? expense, {String? actorName}) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateExpense,
              [expense],
              {#actorName: actorName},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteExpense(String? expenseId, {String? actorName}) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteExpense,
              [expenseId],
              {#actorName: actorName},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void selectExpense(_i7.Expense? expense) => super.noSuchMethod(
    Invocation.method(#selectExpense, [expense]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void emit(_i2.ExpenseState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i9.Change<_i2.ExpenseState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TripCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockTripCubit extends _i1.Mock implements _i10.TripCubit {
  MockTripCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i11.Trip> get trips =>
      (super.noSuchMethod(Invocation.getter(#trips), returnValue: <_i11.Trip>[])
          as List<_i11.Trip>);

  @override
  _i3.TripState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeTripState_1(this, Invocation.getter(#state)),
          )
          as _i3.TripState);

  @override
  _i8.Stream<_i3.TripState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i8.Stream<_i3.TripState>.empty(),
          )
          as _i8.Stream<_i3.TripState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i8.Future<void> loadTrips() =>
      (super.noSuchMethod(
            Invocation.method(#loadTrips, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> createTrip({
    required String? name,
    required List<dynamic>? allowedCurrencies,
    String? creatorName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTrip, [], {
              #name: name,
              #allowedCurrencies: allowedCurrencies,
              #creatorName: creatorName,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> selectTrip(_i11.Trip? trip) =>
      (super.noSuchMethod(
            Invocation.method(#selectTrip, [trip]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateTrip(_i11.Trip? trip) =>
      (super.noSuchMethod(
            Invocation.method(#updateTrip, [trip]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateTripDetails({
    required String? tripId,
    required String? name,
    required dynamic baseCurrency,
    String? actorName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTripDetails, [], {
              #tripId: tripId,
              #name: name,
              #baseCurrency: baseCurrency,
              #actorName: actorName,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateTripCurrencies({
    required String? tripId,
    required List<dynamic>? currencies,
    String? actorName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTripCurrencies, [], {
              #tripId: tripId,
              #currencies: currencies,
              #actorName: actorName,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteTrip(String? tripId, {String? actorName}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTrip, [tripId], {#actorName: actorName}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> archiveTrip(String? tripId, {String? actorName}) =>
      (super.noSuchMethod(
            Invocation.method(#archiveTrip, [tripId], {#actorName: actorName}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> unarchiveTrip(String? tripId, {String? actorName}) =>
      (super.noSuchMethod(
            Invocation.method(
              #unarchiveTrip,
              [tripId],
              {#actorName: actorName},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> leaveTrip(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#leaveTrip, [tripId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> addParticipant({
    required String? tripId,
    required _i12.Participant? participant,
    String? actorName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addParticipant, [], {
              #tripId: tripId,
              #participant: participant,
              #actorName: actorName,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> removeParticipant({
    required String? tripId,
    required _i12.Participant? participant,
    String? actorName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeParticipant, [], {
              #tripId: tripId,
              #participant: participant,
              #actorName: actorName,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> joinTrip({
    required String? tripId,
    required String? userName,
    _i13.JoinMethod? joinMethod,
    String? invitedByParticipantId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#joinTrip, [], {
              #tripId: tripId,
              #userName: userName,
              #joinMethod: joinMethod,
              #invitedByParticipantId: invitedByParticipantId,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> hasDuplicateMember(String? tripId, String? memberName) =>
      (super.noSuchMethod(
            Invocation.method(#hasDuplicateMember, [tripId, memberName]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  bool isUserMemberOf(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#isUserMemberOf, [tripId]),
            returnValue: false,
          )
          as bool);

  @override
  _i8.Future<_i11.Trip?> getTripById(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#getTripById, [tripId]),
            returnValue: _i8.Future<_i11.Trip?>.value(),
          )
          as _i8.Future<_i11.Trip?>);

  @override
  _i8.Future<String> generateRecoveryCode(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#generateRecoveryCode, [tripId]),
            returnValue: _i8.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#generateRecoveryCode, [tripId]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<_i15.TripRecoveryCode?> getRecoveryCode(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#getRecoveryCode, [tripId]),
            returnValue: _i8.Future<_i15.TripRecoveryCode?>.value(),
          )
          as _i8.Future<_i15.TripRecoveryCode?>);

  @override
  _i8.Future<bool> hasRecoveryCode(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#hasRecoveryCode, [tripId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> validateAndJoinWithRecoveryCode({
    required String? tripId,
    required String? code,
    required String? userName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#validateAndJoinWithRecoveryCode, [], {
              #tripId: tripId,
              #code: code,
              #userName: userName,
            }),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i12.Participant? getCurrentUserForTrip(String? tripId) =>
      (super.noSuchMethod(Invocation.method(#getCurrentUserForTrip, [tripId]))
          as _i12.Participant?);

  @override
  _i8.Future<List<_i16.VerifiedMember>> getVerifiedMembers(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#getVerifiedMembers, [tripId]),
            returnValue: _i8.Future<List<_i16.VerifiedMember>>.value(
              <_i16.VerifiedMember>[],
            ),
          )
          as _i8.Future<List<_i16.VerifiedMember>>);

  @override
  _i8.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void emit(_i3.TripState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i9.Change<_i3.TripState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [CategoryCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryCubit extends _i1.Mock implements _i17.CategoryCubit {
  MockCategoryCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.CategoryState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeCategoryState_2(this, Invocation.getter(#state)),
          )
          as _i4.CategoryState);

  @override
  _i8.Stream<_i4.CategoryState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i8.Stream<_i4.CategoryState>.empty(),
          )
          as _i8.Stream<_i4.CategoryState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void loadTopCategories({int? limit = 5}) => super.noSuchMethod(
    Invocation.method(#loadTopCategories, [], {#limit: limit}),
    returnValueForMissingStub: null,
  );

  @override
  void loadTopCategoriesIfStale({int? limit = 5}) => super.noSuchMethod(
    Invocation.method(#loadTopCategoriesIfStale, [], {#limit: limit}),
    returnValueForMissingStub: null,
  );

  @override
  void invalidateTopCategoriesCache() => super.noSuchMethod(
    Invocation.method(#invalidateTopCategoriesCache, []),
    returnValueForMissingStub: null,
  );

  @override
  void resetToTopCategories() => super.noSuchMethod(
    Invocation.method(#resetToTopCategories, []),
    returnValueForMissingStub: null,
  );

  @override
  void searchCategories(String? query) => super.noSuchMethod(
    Invocation.method(#searchCategories, [query]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> createCategory({
    required String? name,
    String? icon = 'label',
    required String? color,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createCategory, [], {
              #name: name,
              #icon: icon,
              #color: color,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> checkRateLimit() =>
      (super.noSuchMethod(
            Invocation.method(#checkRateLimit, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> loadCategoriesByIds(List<String>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#loadCategoriesByIds, [ids]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i18.Category? getCategoryById(String? categoryId) =>
      (super.noSuchMethod(Invocation.method(#getCategoryById, [categoryId]))
          as _i18.Category?);

  @override
  _i8.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void emit(_i4.CategoryState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i9.Change<_i4.CategoryState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [CategoryCustomizationCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryCustomizationCubit extends _i1.Mock
    implements _i19.CategoryCustomizationCubit {
  MockCategoryCustomizationCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.CategoryCustomizationState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeCategoryCustomizationState_3(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i5.CategoryCustomizationState);

  @override
  _i8.Stream<_i5.CategoryCustomizationState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i8.Stream<_i5.CategoryCustomizationState>.empty(),
          )
          as _i8.Stream<_i5.CategoryCustomizationState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i8.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void loadCustomizations() => super.noSuchMethod(
    Invocation.method(#loadCustomizations, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> saveCustomization({
    required String? categoryId,
    String? customIcon,
    String? customColor,
    String? userId,
    String? actorName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveCustomization, [], {
              #categoryId: categoryId,
              #customIcon: customIcon,
              #customColor: customColor,
              #userId: userId,
              #actorName: actorName,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> resetCustomization({
    required String? categoryId,
    String? actorName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetCustomization, [], {
              #categoryId: categoryId,
              #actorName: actorName,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i20.CategoryCustomization? getCustomization(String? categoryId) =>
      (super.noSuchMethod(Invocation.method(#getCustomization, [categoryId]))
          as _i20.CategoryCustomization?);

  @override
  bool isCustomized(String? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#isCustomized, [categoryId]),
            returnValue: false,
          )
          as bool);

  @override
  _i8.Future<bool> hasUserCustomized(String? categoryId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#hasUserCustomized, [categoryId, userId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  void emit(_i5.CategoryCustomizationState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i9.Change<_i5.CategoryCustomizationState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
