// Mocks generated by Mockito 5.4.6 from annotations
// in expense_tracker/test/widget/features/settlements/presentation/pages/settlement_summary_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:expense_tracker/core/models/participant.dart' as _i10;
import 'package:expense_tracker/features/expenses/domain/models/expense.dart'
    as _i4;
import 'package:expense_tracker/features/expenses/domain/repositories/expense_repository.dart'
    as _i15;
import 'package:expense_tracker/features/settlements/presentation/cubits/settlement_cubit.dart'
    as _i5;
import 'package:expense_tracker/features/settlements/presentation/cubits/settlement_state.dart'
    as _i2;
import 'package:expense_tracker/features/trips/domain/models/activity_log.dart'
    as _i11;
import 'package:expense_tracker/features/trips/domain/models/trip.dart' as _i9;
import 'package:expense_tracker/features/trips/domain/models/trip_recovery_code.dart'
    as _i13;
import 'package:expense_tracker/features/trips/domain/models/verified_member.dart'
    as _i14;
import 'package:expense_tracker/features/trips/presentation/cubits/trip_cubit.dart'
    as _i8;
import 'package:expense_tracker/features/trips/presentation/cubits/trip_state.dart'
    as _i3;
import 'package:flutter_bloc/flutter_bloc.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSettlementState_0 extends _i1.SmartFake
    implements _i2.SettlementState {
  _FakeSettlementState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTripState_1 extends _i1.SmartFake implements _i3.TripState {
  _FakeTripState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExpense_2 extends _i1.SmartFake implements _i4.Expense {
  _FakeExpense_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SettlementCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettlementCubit extends _i1.Mock implements _i5.SettlementCubit {
  MockSettlementCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SettlementState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeSettlementState_0(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i2.SettlementState);

  @override
  _i6.Stream<_i2.SettlementState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i2.SettlementState>.empty(),
          )
          as _i6.Stream<_i2.SettlementState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i6.Future<void> loadSettlement(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#loadSettlement, [tripId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> markTransferAsSettled(
    String? transferId, {
    String? actorName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #markTransferAsSettled,
              [transferId],
              {#actorName: actorName},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> computeSettlement(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#computeSettlement, [tripId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> refreshSettlement() =>
      (super.noSuchMethod(
            Invocation.method(#refreshSettlement, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> smartRefresh(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#smartRefresh, [tripId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void setUserFilter(String? userId, _i2.TransferFilterMode? filterMode) =>
      super.noSuchMethod(
        Invocation.method(#setUserFilter, [userId, filterMode]),
        returnValueForMissingStub: null,
      );

  @override
  void clearUserFilter() => super.noSuchMethod(
    Invocation.method(#clearUserFilter, []),
    returnValueForMissingStub: null,
  );

  @override
  void setFilterMode(_i2.TransferFilterMode? filterMode) => super.noSuchMethod(
    Invocation.method(#setFilterMode, [filterMode]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> loadSettlementForCurrency(
    String? tripId,
    dynamic currencyFilter,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#loadSettlementForCurrency, [
              tripId,
              currencyFilter,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void emit(_i2.SettlementState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i7.Change<_i2.SettlementState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TripCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockTripCubit extends _i1.Mock implements _i8.TripCubit {
  MockTripCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i9.Trip> get trips =>
      (super.noSuchMethod(Invocation.getter(#trips), returnValue: <_i9.Trip>[])
          as List<_i9.Trip>);

  @override
  _i3.TripState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeTripState_1(this, Invocation.getter(#state)),
          )
          as _i3.TripState);

  @override
  _i6.Stream<_i3.TripState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i3.TripState>.empty(),
          )
          as _i6.Stream<_i3.TripState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i6.Future<void> loadTrips() =>
      (super.noSuchMethod(
            Invocation.method(#loadTrips, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> createTrip({
    required String? name,
    required List<dynamic>? allowedCurrencies,
    String? creatorName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTrip, [], {
              #name: name,
              #allowedCurrencies: allowedCurrencies,
              #creatorName: creatorName,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> selectTrip(_i9.Trip? trip) =>
      (super.noSuchMethod(
            Invocation.method(#selectTrip, [trip]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateTrip(_i9.Trip? trip) =>
      (super.noSuchMethod(
            Invocation.method(#updateTrip, [trip]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateTripDetails({
    required String? tripId,
    required String? name,
    dynamic baseCurrency,
    String? actorName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTripDetails, [], {
              #tripId: tripId,
              #name: name,
              #baseCurrency: baseCurrency,
              #actorName: actorName,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateTripCurrencies({
    required String? tripId,
    required List<dynamic>? currencies,
    String? actorName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTripCurrencies, [], {
              #tripId: tripId,
              #currencies: currencies,
              #actorName: actorName,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteTrip(String? tripId, {String? actorName}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTrip, [tripId], {#actorName: actorName}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> archiveTrip(String? tripId, {String? actorName}) =>
      (super.noSuchMethod(
            Invocation.method(#archiveTrip, [tripId], {#actorName: actorName}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> unarchiveTrip(String? tripId, {String? actorName}) =>
      (super.noSuchMethod(
            Invocation.method(
              #unarchiveTrip,
              [tripId],
              {#actorName: actorName},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> leaveTrip(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#leaveTrip, [tripId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> addParticipant({
    required String? tripId,
    required _i10.Participant? participant,
    String? actorName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addParticipant, [], {
              #tripId: tripId,
              #participant: participant,
              #actorName: actorName,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeParticipant({
    required String? tripId,
    required _i10.Participant? participant,
    String? actorName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeParticipant, [], {
              #tripId: tripId,
              #participant: participant,
              #actorName: actorName,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> joinTrip({
    required String? tripId,
    required String? userName,
    _i11.JoinMethod? joinMethod,
    String? invitedByParticipantId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#joinTrip, [], {
              #tripId: tripId,
              #userName: userName,
              #joinMethod: joinMethod,
              #invitedByParticipantId: invitedByParticipantId,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> hasDuplicateMember(String? tripId, String? memberName) =>
      (super.noSuchMethod(
            Invocation.method(#hasDuplicateMember, [tripId, memberName]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> isUserMemberOf(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#isUserMemberOf, [tripId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i9.Trip?> getTripById(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#getTripById, [tripId]),
            returnValue: _i6.Future<_i9.Trip?>.value(),
          )
          as _i6.Future<_i9.Trip?>);

  @override
  _i6.Future<String> generateRecoveryCode(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#generateRecoveryCode, [tripId]),
            returnValue: _i6.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#generateRecoveryCode, [tripId]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<_i13.TripRecoveryCode?> getRecoveryCode(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#getRecoveryCode, [tripId]),
            returnValue: _i6.Future<_i13.TripRecoveryCode?>.value(),
          )
          as _i6.Future<_i13.TripRecoveryCode?>);

  @override
  _i6.Future<bool> hasRecoveryCode(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#hasRecoveryCode, [tripId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> validateAndJoinWithRecoveryCode({
    required String? tripId,
    required String? code,
    required String? userName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#validateAndJoinWithRecoveryCode, [], {
              #tripId: tripId,
              #code: code,
              #userName: userName,
            }),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i10.Participant?> getCurrentUserForTrip(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUserForTrip, [tripId]),
            returnValue: _i6.Future<_i10.Participant?>.value(),
          )
          as _i6.Future<_i10.Participant?>);

  @override
  _i6.Future<List<_i14.VerifiedMember>> getVerifiedMembers(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#getVerifiedMembers, [tripId]),
            returnValue: _i6.Future<List<_i14.VerifiedMember>>.value(
              <_i14.VerifiedMember>[],
            ),
          )
          as _i6.Future<List<_i14.VerifiedMember>>);

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void emit(_i3.TripState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i7.Change<_i3.TripState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ExpenseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpenseRepository extends _i1.Mock implements _i15.ExpenseRepository {
  MockExpenseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Expense> createExpense(_i4.Expense? expense) =>
      (super.noSuchMethod(
            Invocation.method(#createExpense, [expense]),
            returnValue: _i6.Future<_i4.Expense>.value(
              _FakeExpense_2(
                this,
                Invocation.method(#createExpense, [expense]),
              ),
            ),
          )
          as _i6.Future<_i4.Expense>);

  @override
  _i6.Future<_i4.Expense?> getExpenseById(String? expenseId) =>
      (super.noSuchMethod(
            Invocation.method(#getExpenseById, [expenseId]),
            returnValue: _i6.Future<_i4.Expense?>.value(),
          )
          as _i6.Future<_i4.Expense?>);

  @override
  _i6.Stream<List<_i4.Expense>> getExpensesByTrip(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#getExpensesByTrip, [tripId]),
            returnValue: _i6.Stream<List<_i4.Expense>>.empty(),
          )
          as _i6.Stream<List<_i4.Expense>>);

  @override
  _i6.Future<_i4.Expense> updateExpense(_i4.Expense? expense) =>
      (super.noSuchMethod(
            Invocation.method(#updateExpense, [expense]),
            returnValue: _i6.Future<_i4.Expense>.value(
              _FakeExpense_2(
                this,
                Invocation.method(#updateExpense, [expense]),
              ),
            ),
          )
          as _i6.Future<_i4.Expense>);

  @override
  _i6.Future<void> deleteExpense(String? expenseId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteExpense, [expenseId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> expenseExists(String? expenseId) =>
      (super.noSuchMethod(
            Invocation.method(#expenseExists, [expenseId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Stream<List<_i4.Expense>> getExpensesByCategory(
    String? tripId,
    String? categoryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExpensesByCategory, [tripId, categoryId]),
            returnValue: _i6.Stream<List<_i4.Expense>>.empty(),
          )
          as _i6.Stream<List<_i4.Expense>>);

  @override
  _i6.Stream<List<_i4.Expense>> getExpensesByPayer(
    String? tripId,
    String? payerUserId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExpensesByPayer, [tripId, payerUserId]),
            returnValue: _i6.Stream<List<_i4.Expense>>.empty(),
          )
          as _i6.Stream<List<_i4.Expense>>);
}
