// Mocks generated by Mockito 5.4.6 from annotations
// in expense_tracker/test/features/categories/presentation/cubit/category_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:expense_tracker/features/categories/data/services/rate_limiter_service.dart'
    as _i5;
import 'package:expense_tracker/features/categories/domain/models/category.dart'
    as _i2;
import 'package:expense_tracker/features/categories/domain/repositories/category_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCategory_0 extends _i1.SmartFake implements _i2.Category {
  _FakeCategory_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i3.CategoryRepository {
  MockCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i2.Category>> getTopCategories({int? limit = 5}) =>
      (super.noSuchMethod(
            Invocation.method(#getTopCategories, [], {#limit: limit}),
            returnValue: _i4.Stream<List<_i2.Category>>.empty(),
          )
          as _i4.Stream<List<_i2.Category>>);

  @override
  _i4.Stream<List<_i2.Category>> searchCategories(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchCategories, [query]),
            returnValue: _i4.Stream<List<_i2.Category>>.empty(),
          )
          as _i4.Stream<List<_i2.Category>>);

  @override
  _i4.Future<_i2.Category?> getCategoryById(String? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#getCategoryById, [categoryId]),
            returnValue: _i4.Future<_i2.Category?>.value(),
          )
          as _i4.Future<_i2.Category?>);

  @override
  _i4.Future<_i2.Category> createCategory({
    required String? name,
    String? icon = 'label',
    required String? color,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createCategory, [], {
              #name: name,
              #icon: icon,
              #color: color,
              #userId: userId,
            }),
            returnValue: _i4.Future<_i2.Category>.value(
              _FakeCategory_0(
                this,
                Invocation.method(#createCategory, [], {
                  #name: name,
                  #icon: icon,
                  #color: color,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Category>);

  @override
  _i4.Future<void> incrementCategoryUsage(String? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#incrementCategoryUsage, [categoryId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> categoryExists(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#categoryExists, [name]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> canUserCreateCategory(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#canUserCreateCategory, [userId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<_i2.Category>> seedDefaultCategories() =>
      (super.noSuchMethod(
            Invocation.method(#seedDefaultCategories, []),
            returnValue: _i4.Future<List<_i2.Category>>.value(<_i2.Category>[]),
          )
          as _i4.Future<List<_i2.Category>>);
}

/// A class which mocks [RateLimiterService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRateLimiterService extends _i1.Mock
    implements _i5.RateLimiterService {
  MockRateLimiterService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> canUserCreateCategory(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#canUserCreateCategory, [userId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> logCategoryCreation({
    required String? userId,
    required String? categoryId,
    required String? categoryName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logCategoryCreation, [], {
              #userId: userId,
              #categoryId: categoryId,
              #categoryName: categoryName,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> getRecentCreationCount(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentCreationCount, [userId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<Duration?> getTimeUntilNextCreation(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getTimeUntilNextCreation, [userId]),
            returnValue: _i4.Future<Duration?>.value(),
          )
          as _i4.Future<Duration?>);
}
