//
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by: CurrencyCodeGenerator
// Source: assets/currencies.json
// Generated at: 2025-11-01T13:44:21.675647Z
//

part of 'currency_code.dart';

/// ISO 4217 currency codes with metadata
///
/// This enum is generated from assets/currencies.json
/// To update: modify JSON file and run `dart run build_runner build`
enum CurrencyCode {
  /// United Arab Emirates Dirham (AED, 2 decimals)
  aed('AED', 2),

  /// Afghan Afghani (؋, 2 decimals)
  afn('AFN', 2),

  /// Albanian Lek (L, 2 decimals)
  all('ALL', 2),

  /// Armenian Dram (֏, 2 decimals)
  amd('AMD', 2),

  /// Netherlands Antillean Guilder (ƒ, 2 decimals)
  ang('ANG', 2),

  /// Angolan Kwanza (Kz, 2 decimals)
  aoa('AOA', 2),

  /// Argentine Peso ($, 2 decimals)
  ars('ARS', 2),

  /// Australian Dollar (A$, 2 decimals)
  aud('AUD', 2),

  /// Aruban Florin (ƒ, 2 decimals)
  awg('AWG', 2),

  /// Azerbaijani Manat (₼, 2 decimals)
  azn('AZN', 2),

  /// Bosnia-Herzegovina Convertible Mark (KM, 2 decimals)
  bam('BAM', 2),

  /// Barbadian Dollar (Bds$, 2 decimals)
  bbd('BBD', 2),

  /// Bangladeshi Taka (৳, 2 decimals)
  bdt('BDT', 2),

  /// Bulgarian Lev (лв, 2 decimals)
  bgn('BGN', 2),

  /// Bahraini Dinar (BD, 3 decimals)
  bhd('BHD', 3),

  /// Burundian Franc (FBu, 0 decimals)
  bif('BIF', 0),

  /// Bermudan Dollar (BD$, 2 decimals)
  bmd('BMD', 2),

  /// Brunei Dollar (B$, 2 decimals)
  bnd('BND', 2),

  /// Bolivian Boliviano (Bs, 2 decimals)
  bob('BOB', 2),

  /// Brazilian Real (R$, 2 decimals)
  brl('BRL', 2),

  /// Bahamian Dollar (B$, 2 decimals)
  bsd('BSD', 2),

  /// Bhutanese Ngultrum (Nu., 2 decimals)
  btn('BTN', 2),

  /// Botswanan Pula (P, 2 decimals)
  bwp('BWP', 2),

  /// Belarusian Ruble (Br, 2 decimals)
  byn('BYN', 2),

  /// Belize Dollar (BZ$, 2 decimals)
  bzd('BZD', 2),

  /// Canadian Dollar (CA$, 2 decimals)
  cad('CAD', 2),

  /// Congolese Franc (FC, 2 decimals)
  cdf('CDF', 2),

  /// Swiss Franc (CHF, 2 decimals)
  chf('CHF', 2),

  /// Chilean Peso ($, 0 decimals)
  clp('CLP', 0),

  /// Chinese Yuan (¥, 2 decimals)
  cny('CNY', 2),

  /// Colombian Peso ($, 2 decimals)
  cop('COP', 2),

  /// Costa Rican Colón (₡, 2 decimals)
  crc('CRC', 2),

  /// Cuban Peso ($, 2 decimals)
  cup('CUP', 2),

  /// Cape Verdean Escudo ($, 2 decimals)
  cve('CVE', 2),

  /// Czech Koruna (Kč, 2 decimals)
  czk('CZK', 2),

  /// Djiboutian Franc (Fdj, 0 decimals)
  djf('DJF', 0),

  /// Danish Krone (kr, 2 decimals)
  dkk('DKK', 2),

  /// Dominican Peso (RD$, 2 decimals)
  dop('DOP', 2),

  /// Algerian Dinar (DA, 2 decimals)
  dzd('DZD', 2),

  /// Egyptian Pound (E£, 2 decimals)
  egp('EGP', 2),

  /// Eritrean Nakfa (Nfk, 2 decimals)
  ern('ERN', 2),

  /// Ethiopian Birr (Br, 2 decimals)
  etb('ETB', 2),

  /// Euro (€, 2 decimals)
  eur('EUR', 2),

  /// Fijian Dollar (FJ$, 2 decimals)
  fjd('FJD', 2),

  /// Falkland Islands Pound (£, 2 decimals)
  fkp('FKP', 2),

  /// British Pound Sterling (£, 2 decimals)
  gbp('GBP', 2),

  /// Georgian Lari (₾, 2 decimals)
  gel('GEL', 2),

  /// Ghanaian Cedi (GH₵, 2 decimals)
  ghs('GHS', 2),

  /// Gibraltar Pound (£, 2 decimals)
  gip('GIP', 2),

  /// Gambian Dalasi (D, 2 decimals)
  gmd('GMD', 2),

  /// Guinean Franc (FG, 0 decimals)
  gnf('GNF', 0),

  /// Guatemalan Quetzal (Q, 2 decimals)
  gtq('GTQ', 2),

  /// Guyanaese Dollar (GY$, 2 decimals)
  gyd('GYD', 2),

  /// Hong Kong Dollar (HK$, 2 decimals)
  hkd('HKD', 2),

  /// Honduran Lempira (L, 2 decimals)
  hnl('HNL', 2),

  /// Croatian Kuna (kn, 2 decimals)
  hrk('HRK', 2),

  /// Haitian Gourde (G, 2 decimals)
  htg('HTG', 2),

  /// Hungarian Forint (Ft, 2 decimals)
  huf('HUF', 2),

  /// Indonesian Rupiah (Rp, 2 decimals)
  idr('IDR', 2),

  /// Israeli New Shekel (₪, 2 decimals)
  ils('ILS', 2),

  /// Indian Rupee (₹, 2 decimals)
  inr('INR', 2),

  /// Iraqi Dinar (IQD, 3 decimals)
  iqd('IQD', 3),

  /// Iranian Rial (﷼, 2 decimals)
  irr('IRR', 2),

  /// Icelandic Króna (kr, 0 decimals)
  isk('ISK', 0),

  /// Jamaican Dollar (J$, 2 decimals)
  jmd('JMD', 2),

  /// Jordanian Dinar (JD, 3 decimals)
  jod('JOD', 3),

  /// Japanese Yen (¥, 0 decimals)
  jpy('JPY', 0),

  /// Kenyan Shilling (KSh, 2 decimals)
  kes('KES', 2),

  /// Kyrgystani Som (с, 2 decimals)
  kgs('KGS', 2),

  /// Cambodian Riel (៛, 2 decimals)
  khr('KHR', 2),

  /// Comorian Franc (CF, 0 decimals)
  kmf('KMF', 0),

  /// North Korean Won (₩, 2 decimals)
  kpw('KPW', 2),

  /// South Korean Won (₩, 0 decimals)
  krw('KRW', 0),

  /// Kuwaiti Dinar (KD, 3 decimals)
  kwd('KWD', 3),

  /// Cayman Islands Dollar (CI$, 2 decimals)
  kyd('KYD', 2),

  /// Kazakhstani Tenge (₸, 2 decimals)
  kzt('KZT', 2),

  /// Laotian Kip (₭, 2 decimals)
  lak('LAK', 2),

  /// Lebanese Pound (L£, 2 decimals)
  lbp('LBP', 2),

  /// Sri Lankan Rupee (Rs, 2 decimals)
  lkr('LKR', 2),

  /// Liberian Dollar (L$, 2 decimals)
  lrd('LRD', 2),

  /// Lesotho Loti (L, 2 decimals)
  lsl('LSL', 2),

  /// Libyan Dinar (LD, 3 decimals)
  lyd('LYD', 3),

  /// Moroccan Dirham (MAD, 2 decimals)
  mad('MAD', 2),

  /// Moldovan Leu (L, 2 decimals)
  mdl('MDL', 2),

  /// Malagasy Ariary (Ar, 2 decimals)
  mga('MGA', 2),

  /// Macedonian Denar (ден, 2 decimals)
  mkd('MKD', 2),

  /// Myanmar Kyat (K, 2 decimals)
  mmk('MMK', 2),

  /// Mongolian Tugrik (₮, 2 decimals)
  mnt('MNT', 2),

  /// Macanese Pataca (MOP$, 2 decimals)
  mop('MOP', 2),

  /// Mauritanian Ouguiya (UM, 2 decimals)
  mru('MRU', 2),

  /// Mauritian Rupee (₨, 2 decimals)
  mur('MUR', 2),

  /// Maldivian Rufiyaa (Rf, 2 decimals)
  mvr('MVR', 2),

  /// Malawian Kwacha (MK, 2 decimals)
  mwk('MWK', 2),

  /// Mexican Peso ($, 2 decimals)
  mxn('MXN', 2),

  /// Malaysian Ringgit (RM, 2 decimals)
  myr('MYR', 2),

  /// Mozambican Metical (MT, 2 decimals)
  mzn('MZN', 2),

  /// Namibian Dollar (N$, 2 decimals)
  nad('NAD', 2),

  /// Nigerian Naira (₦, 2 decimals)
  ngn('NGN', 2),

  /// Nicaraguan Córdoba (C$, 2 decimals)
  nio('NIO', 2),

  /// Norwegian Krone (kr, 2 decimals)
  nok('NOK', 2),

  /// Nepalese Rupee (₨, 2 decimals)
  npr('NPR', 2),

  /// New Zealand Dollar (NZ$, 2 decimals)
  nzd('NZD', 2),

  /// Omani Rial (OMR, 3 decimals)
  omr('OMR', 3),

  /// Panamanian Balboa (B/., 2 decimals)
  pab('PAB', 2),

  /// Peruvian Nuevo Sol (S/, 2 decimals)
  pen('PEN', 2),

  /// Papua New Guinean Kina (K, 2 decimals)
  pgk('PGK', 2),

  /// Philippine Peso (₱, 2 decimals)
  php('PHP', 2),

  /// Pakistani Rupee (₨, 2 decimals)
  pkr('PKR', 2),

  /// Polish Zloty (zł, 2 decimals)
  pln('PLN', 2),

  /// Paraguayan Guarani (₲, 0 decimals)
  pyg('PYG', 0),

  /// Qatari Rial (QR, 2 decimals)
  qar('QAR', 2),

  /// Romanian Leu (lei, 2 decimals)
  ron('RON', 2),

  /// Serbian Dinar (din, 2 decimals)
  rsd('RSD', 2),

  /// Russian Ruble (₽, 2 decimals)
  rub('RUB', 2),

  /// Rwandan Franc (FRw, 0 decimals)
  rwf('RWF', 0),

  /// Saudi Riyal (SR, 2 decimals)
  sar('SAR', 2),

  /// Solomon Islands Dollar (SI$, 2 decimals)
  sbd('SBD', 2),

  /// Seychellois Rupee (SR, 2 decimals)
  scr('SCR', 2),

  /// Sudanese Pound (SDG, 2 decimals)
  sdg('SDG', 2),

  /// Swedish Krona (kr, 2 decimals)
  sek('SEK', 2),

  /// Singapore Dollar (S$, 2 decimals)
  sgd('SGD', 2),

  /// Saint Helena Pound (£, 2 decimals)
  shp('SHP', 2),

  /// Sierra Leonean Leone (Le, 2 decimals)
  sll('SLL', 2),

  /// Somali Shilling (Sh, 2 decimals)
  sos('SOS', 2),

  /// Surinamese Dollar ($, 2 decimals)
  srd('SRD', 2),

  /// South Sudanese Pound (SSP, 2 decimals)
  ssp('SSP', 2),

  /// São Tomé and Príncipe Dobra (Db, 2 decimals)
  stn('STN', 2),

  /// Syrian Pound (£S, 2 decimals)
  syp('SYP', 2),

  /// Swazi Lilangeni (L, 2 decimals)
  szl('SZL', 2),

  /// Thai Baht (฿, 2 decimals)
  thb('THB', 2),

  /// Tajikistani Somoni (ЅМ, 2 decimals)
  tjs('TJS', 2),

  /// Turkmenistani Manat (m, 2 decimals)
  tmt('TMT', 2),

  /// Tunisian Dinar (DT, 3 decimals)
  tnd('TND', 3),

  /// Tongan Paʻanga (T$, 2 decimals)
  top('TOP', 2),

  /// Turkish Lira (₺, 2 decimals)
  try('TRY', 2),

  /// Trinidad and Tobago Dollar (TT$, 2 decimals)
  ttd('TTD', 2),

  /// New Taiwan Dollar (NT$, 2 decimals)
  twd('TWD', 2),

  /// Tanzanian Shilling (TSh, 2 decimals)
  tzs('TZS', 2),

  /// Ukrainian Hryvnia (₴, 2 decimals)
  uah('UAH', 2),

  /// Ugandan Shilling (USh, 0 decimals)
  ugx('UGX', 0),

  /// United States Dollar ($, 2 decimals)
  usd('USD', 2),

  /// Uruguayan Peso ($U, 2 decimals)
  uyu('UYU', 2),

  /// Uzbekistan Som (сўм, 2 decimals)
  uzs('UZS', 2),

  /// Venezuelan Bolívar (Bs.S, 2 decimals)
  ves('VES', 2),

  /// Vietnamese Dong (₫, 0 decimals)
  vnd('VND', 0),

  /// Vanuatu Vatu (VT, 0 decimals)
  vuv('VUV', 0),

  /// Samoan Tala (WS$, 2 decimals)
  wst('WST', 2),

  /// Central African CFA Franc (FCFA, 0 decimals)
  xaf('XAF', 0),

  /// East Caribbean Dollar (EC$, 2 decimals)
  xcd('XCD', 2),

  /// West African CFA Franc (CFA, 0 decimals)
  xof('XOF', 0),

  /// CFP Franc (₣, 0 decimals)
  xpf('XPF', 0),

  /// Yemeni Rial (YR, 2 decimals)
  yer('YER', 2),

  /// South African Rand (R, 2 decimals)
  zar('ZAR', 2),

  /// Zambian Kwacha (ZK, 2 decimals)
  zmw('ZMW', 2),

  /// Zimbabwean Dollar (Z$, 2 decimals)
  zwl('ZWL', 2);

  /// ISO 4217 alphabetic code (e.g., "USD", "EUR")
  final String code;

  /// Number of decimal places (minor units): 0, 2, or 3
  final int decimalPlaces;

  const CurrencyCode(this.code, this.decimalPlaces);

  /// Parse currency code string to enum
  ///
  /// Returns null if code is invalid
  /// Case-insensitive matching
  static CurrencyCode? fromString(String? code) {
    if (code == null || code.isEmpty) return null;

    final normalized = code.trim().toUpperCase();

    switch (normalized) {
      case 'AED': return CurrencyCode.aed;
      case 'AFN': return CurrencyCode.afn;
      case 'ALL': return CurrencyCode.all;
      case 'AMD': return CurrencyCode.amd;
      case 'ANG': return CurrencyCode.ang;
      case 'AOA': return CurrencyCode.aoa;
      case 'ARS': return CurrencyCode.ars;
      case 'AUD': return CurrencyCode.aud;
      case 'AWG': return CurrencyCode.awg;
      case 'AZN': return CurrencyCode.azn;
      case 'BAM': return CurrencyCode.bam;
      case 'BBD': return CurrencyCode.bbd;
      case 'BDT': return CurrencyCode.bdt;
      case 'BGN': return CurrencyCode.bgn;
      case 'BHD': return CurrencyCode.bhd;
      case 'BIF': return CurrencyCode.bif;
      case 'BMD': return CurrencyCode.bmd;
      case 'BND': return CurrencyCode.bnd;
      case 'BOB': return CurrencyCode.bob;
      case 'BRL': return CurrencyCode.brl;
      case 'BSD': return CurrencyCode.bsd;
      case 'BTN': return CurrencyCode.btn;
      case 'BWP': return CurrencyCode.bwp;
      case 'BYN': return CurrencyCode.byn;
      case 'BZD': return CurrencyCode.bzd;
      case 'CAD': return CurrencyCode.cad;
      case 'CDF': return CurrencyCode.cdf;
      case 'CHF': return CurrencyCode.chf;
      case 'CLP': return CurrencyCode.clp;
      case 'CNY': return CurrencyCode.cny;
      case 'COP': return CurrencyCode.cop;
      case 'CRC': return CurrencyCode.crc;
      case 'CUP': return CurrencyCode.cup;
      case 'CVE': return CurrencyCode.cve;
      case 'CZK': return CurrencyCode.czk;
      case 'DJF': return CurrencyCode.djf;
      case 'DKK': return CurrencyCode.dkk;
      case 'DOP': return CurrencyCode.dop;
      case 'DZD': return CurrencyCode.dzd;
      case 'EGP': return CurrencyCode.egp;
      case 'ERN': return CurrencyCode.ern;
      case 'ETB': return CurrencyCode.etb;
      case 'EUR': return CurrencyCode.eur;
      case 'FJD': return CurrencyCode.fjd;
      case 'FKP': return CurrencyCode.fkp;
      case 'GBP': return CurrencyCode.gbp;
      case 'GEL': return CurrencyCode.gel;
      case 'GHS': return CurrencyCode.ghs;
      case 'GIP': return CurrencyCode.gip;
      case 'GMD': return CurrencyCode.gmd;
      case 'GNF': return CurrencyCode.gnf;
      case 'GTQ': return CurrencyCode.gtq;
      case 'GYD': return CurrencyCode.gyd;
      case 'HKD': return CurrencyCode.hkd;
      case 'HNL': return CurrencyCode.hnl;
      case 'HRK': return CurrencyCode.hrk;
      case 'HTG': return CurrencyCode.htg;
      case 'HUF': return CurrencyCode.huf;
      case 'IDR': return CurrencyCode.idr;
      case 'ILS': return CurrencyCode.ils;
      case 'INR': return CurrencyCode.inr;
      case 'IQD': return CurrencyCode.iqd;
      case 'IRR': return CurrencyCode.irr;
      case 'ISK': return CurrencyCode.isk;
      case 'JMD': return CurrencyCode.jmd;
      case 'JOD': return CurrencyCode.jod;
      case 'JPY': return CurrencyCode.jpy;
      case 'KES': return CurrencyCode.kes;
      case 'KGS': return CurrencyCode.kgs;
      case 'KHR': return CurrencyCode.khr;
      case 'KMF': return CurrencyCode.kmf;
      case 'KPW': return CurrencyCode.kpw;
      case 'KRW': return CurrencyCode.krw;
      case 'KWD': return CurrencyCode.kwd;
      case 'KYD': return CurrencyCode.kyd;
      case 'KZT': return CurrencyCode.kzt;
      case 'LAK': return CurrencyCode.lak;
      case 'LBP': return CurrencyCode.lbp;
      case 'LKR': return CurrencyCode.lkr;
      case 'LRD': return CurrencyCode.lrd;
      case 'LSL': return CurrencyCode.lsl;
      case 'LYD': return CurrencyCode.lyd;
      case 'MAD': return CurrencyCode.mad;
      case 'MDL': return CurrencyCode.mdl;
      case 'MGA': return CurrencyCode.mga;
      case 'MKD': return CurrencyCode.mkd;
      case 'MMK': return CurrencyCode.mmk;
      case 'MNT': return CurrencyCode.mnt;
      case 'MOP': return CurrencyCode.mop;
      case 'MRU': return CurrencyCode.mru;
      case 'MUR': return CurrencyCode.mur;
      case 'MVR': return CurrencyCode.mvr;
      case 'MWK': return CurrencyCode.mwk;
      case 'MXN': return CurrencyCode.mxn;
      case 'MYR': return CurrencyCode.myr;
      case 'MZN': return CurrencyCode.mzn;
      case 'NAD': return CurrencyCode.nad;
      case 'NGN': return CurrencyCode.ngn;
      case 'NIO': return CurrencyCode.nio;
      case 'NOK': return CurrencyCode.nok;
      case 'NPR': return CurrencyCode.npr;
      case 'NZD': return CurrencyCode.nzd;
      case 'OMR': return CurrencyCode.omr;
      case 'PAB': return CurrencyCode.pab;
      case 'PEN': return CurrencyCode.pen;
      case 'PGK': return CurrencyCode.pgk;
      case 'PHP': return CurrencyCode.php;
      case 'PKR': return CurrencyCode.pkr;
      case 'PLN': return CurrencyCode.pln;
      case 'PYG': return CurrencyCode.pyg;
      case 'QAR': return CurrencyCode.qar;
      case 'RON': return CurrencyCode.ron;
      case 'RSD': return CurrencyCode.rsd;
      case 'RUB': return CurrencyCode.rub;
      case 'RWF': return CurrencyCode.rwf;
      case 'SAR': return CurrencyCode.sar;
      case 'SBD': return CurrencyCode.sbd;
      case 'SCR': return CurrencyCode.scr;
      case 'SDG': return CurrencyCode.sdg;
      case 'SEK': return CurrencyCode.sek;
      case 'SGD': return CurrencyCode.sgd;
      case 'SHP': return CurrencyCode.shp;
      case 'SLL': return CurrencyCode.sll;
      case 'SOS': return CurrencyCode.sos;
      case 'SRD': return CurrencyCode.srd;
      case 'SSP': return CurrencyCode.ssp;
      case 'STN': return CurrencyCode.stn;
      case 'SYP': return CurrencyCode.syp;
      case 'SZL': return CurrencyCode.szl;
      case 'THB': return CurrencyCode.thb;
      case 'TJS': return CurrencyCode.tjs;
      case 'TMT': return CurrencyCode.tmt;
      case 'TND': return CurrencyCode.tnd;
      case 'TOP': return CurrencyCode.top;
      case 'TRY': return CurrencyCode.try;
      case 'TTD': return CurrencyCode.ttd;
      case 'TWD': return CurrencyCode.twd;
      case 'TZS': return CurrencyCode.tzs;
      case 'UAH': return CurrencyCode.uah;
      case 'UGX': return CurrencyCode.ugx;
      case 'USD': return CurrencyCode.usd;
      case 'UYU': return CurrencyCode.uyu;
      case 'UZS': return CurrencyCode.uzs;
      case 'VES': return CurrencyCode.ves;
      case 'VND': return CurrencyCode.vnd;
      case 'VUV': return CurrencyCode.vuv;
      case 'WST': return CurrencyCode.wst;
      case 'XAF': return CurrencyCode.xaf;
      case 'XCD': return CurrencyCode.xcd;
      case 'XOF': return CurrencyCode.xof;
      case 'XPF': return CurrencyCode.xpf;
      case 'YER': return CurrencyCode.yer;
      case 'ZAR': return CurrencyCode.zar;
      case 'ZMW': return CurrencyCode.zmw;
      case 'ZWL': return CurrencyCode.zwl;
      default: return null;
    }
  }

  /// Get all active currencies (for currency picker)
  static List<CurrencyCode> get activeCurrencies {
    return CurrencyCode.values.where((c) => c.isActive).toList();
  }
}

/// Extension methods for CurrencyCode
extension CurrencyCodeExtension on CurrencyCode {
  /// Currency symbol or code fallback
  String get symbol {
    switch (this) {
      case CurrencyCode.aed: return 'AED';
      case CurrencyCode.afn: return '؋';
      case CurrencyCode.all: return 'L';
      case CurrencyCode.amd: return '֏';
      case CurrencyCode.ang: return 'ƒ';
      case CurrencyCode.aoa: return 'Kz';
      case CurrencyCode.ars: return '\$';
      case CurrencyCode.aud: return 'A\$';
      case CurrencyCode.awg: return 'ƒ';
      case CurrencyCode.azn: return '₼';
      case CurrencyCode.bam: return 'KM';
      case CurrencyCode.bbd: return 'Bds\$';
      case CurrencyCode.bdt: return '৳';
      case CurrencyCode.bgn: return 'лв';
      case CurrencyCode.bhd: return 'BD';
      case CurrencyCode.bif: return 'FBu';
      case CurrencyCode.bmd: return 'BD\$';
      case CurrencyCode.bnd: return 'B\$';
      case CurrencyCode.bob: return 'Bs';
      case CurrencyCode.brl: return 'R\$';
      case CurrencyCode.bsd: return 'B\$';
      case CurrencyCode.btn: return 'Nu.';
      case CurrencyCode.bwp: return 'P';
      case CurrencyCode.byn: return 'Br';
      case CurrencyCode.bzd: return 'BZ\$';
      case CurrencyCode.cad: return 'CA\$';
      case CurrencyCode.cdf: return 'FC';
      case CurrencyCode.chf: return 'CHF';
      case CurrencyCode.clp: return '\$';
      case CurrencyCode.cny: return '¥';
      case CurrencyCode.cop: return '\$';
      case CurrencyCode.crc: return '₡';
      case CurrencyCode.cup: return '\$';
      case CurrencyCode.cve: return '\$';
      case CurrencyCode.czk: return 'Kč';
      case CurrencyCode.djf: return 'Fdj';
      case CurrencyCode.dkk: return 'kr';
      case CurrencyCode.dop: return 'RD\$';
      case CurrencyCode.dzd: return 'DA';
      case CurrencyCode.egp: return 'E£';
      case CurrencyCode.ern: return 'Nfk';
      case CurrencyCode.etb: return 'Br';
      case CurrencyCode.eur: return '€';
      case CurrencyCode.fjd: return 'FJ\$';
      case CurrencyCode.fkp: return '£';
      case CurrencyCode.gbp: return '£';
      case CurrencyCode.gel: return '₾';
      case CurrencyCode.ghs: return 'GH₵';
      case CurrencyCode.gip: return '£';
      case CurrencyCode.gmd: return 'D';
      case CurrencyCode.gnf: return 'FG';
      case CurrencyCode.gtq: return 'Q';
      case CurrencyCode.gyd: return 'GY\$';
      case CurrencyCode.hkd: return 'HK\$';
      case CurrencyCode.hnl: return 'L';
      case CurrencyCode.hrk: return 'kn';
      case CurrencyCode.htg: return 'G';
      case CurrencyCode.huf: return 'Ft';
      case CurrencyCode.idr: return 'Rp';
      case CurrencyCode.ils: return '₪';
      case CurrencyCode.inr: return '₹';
      case CurrencyCode.iqd: return 'IQD';
      case CurrencyCode.irr: return '﷼';
      case CurrencyCode.isk: return 'kr';
      case CurrencyCode.jmd: return 'J\$';
      case CurrencyCode.jod: return 'JD';
      case CurrencyCode.jpy: return '¥';
      case CurrencyCode.kes: return 'KSh';
      case CurrencyCode.kgs: return 'с';
      case CurrencyCode.khr: return '៛';
      case CurrencyCode.kmf: return 'CF';
      case CurrencyCode.kpw: return '₩';
      case CurrencyCode.krw: return '₩';
      case CurrencyCode.kwd: return 'KD';
      case CurrencyCode.kyd: return 'CI\$';
      case CurrencyCode.kzt: return '₸';
      case CurrencyCode.lak: return '₭';
      case CurrencyCode.lbp: return 'L£';
      case CurrencyCode.lkr: return 'Rs';
      case CurrencyCode.lrd: return 'L\$';
      case CurrencyCode.lsl: return 'L';
      case CurrencyCode.lyd: return 'LD';
      case CurrencyCode.mad: return 'MAD';
      case CurrencyCode.mdl: return 'L';
      case CurrencyCode.mga: return 'Ar';
      case CurrencyCode.mkd: return 'ден';
      case CurrencyCode.mmk: return 'K';
      case CurrencyCode.mnt: return '₮';
      case CurrencyCode.mop: return 'MOP\$';
      case CurrencyCode.mru: return 'UM';
      case CurrencyCode.mur: return '₨';
      case CurrencyCode.mvr: return 'Rf';
      case CurrencyCode.mwk: return 'MK';
      case CurrencyCode.mxn: return '\$';
      case CurrencyCode.myr: return 'RM';
      case CurrencyCode.mzn: return 'MT';
      case CurrencyCode.nad: return 'N\$';
      case CurrencyCode.ngn: return '₦';
      case CurrencyCode.nio: return 'C\$';
      case CurrencyCode.nok: return 'kr';
      case CurrencyCode.npr: return '₨';
      case CurrencyCode.nzd: return 'NZ\$';
      case CurrencyCode.omr: return 'OMR';
      case CurrencyCode.pab: return 'B/.';
      case CurrencyCode.pen: return 'S/';
      case CurrencyCode.pgk: return 'K';
      case CurrencyCode.php: return '₱';
      case CurrencyCode.pkr: return '₨';
      case CurrencyCode.pln: return 'zł';
      case CurrencyCode.pyg: return '₲';
      case CurrencyCode.qar: return 'QR';
      case CurrencyCode.ron: return 'lei';
      case CurrencyCode.rsd: return 'din';
      case CurrencyCode.rub: return '₽';
      case CurrencyCode.rwf: return 'FRw';
      case CurrencyCode.sar: return 'SR';
      case CurrencyCode.sbd: return 'SI\$';
      case CurrencyCode.scr: return 'SR';
      case CurrencyCode.sdg: return 'SDG';
      case CurrencyCode.sek: return 'kr';
      case CurrencyCode.sgd: return 'S\$';
      case CurrencyCode.shp: return '£';
      case CurrencyCode.sll: return 'Le';
      case CurrencyCode.sos: return 'Sh';
      case CurrencyCode.srd: return '\$';
      case CurrencyCode.ssp: return 'SSP';
      case CurrencyCode.stn: return 'Db';
      case CurrencyCode.syp: return '£S';
      case CurrencyCode.szl: return 'L';
      case CurrencyCode.thb: return '฿';
      case CurrencyCode.tjs: return 'ЅМ';
      case CurrencyCode.tmt: return 'm';
      case CurrencyCode.tnd: return 'DT';
      case CurrencyCode.top: return 'T\$';
      case CurrencyCode.try: return '₺';
      case CurrencyCode.ttd: return 'TT\$';
      case CurrencyCode.twd: return 'NT\$';
      case CurrencyCode.tzs: return 'TSh';
      case CurrencyCode.uah: return '₴';
      case CurrencyCode.ugx: return 'USh';
      case CurrencyCode.usd: return '\$';
      case CurrencyCode.uyu: return '\$U';
      case CurrencyCode.uzs: return 'сўм';
      case CurrencyCode.ves: return 'Bs.S';
      case CurrencyCode.vnd: return '₫';
      case CurrencyCode.vuv: return 'VT';
      case CurrencyCode.wst: return 'WS\$';
      case CurrencyCode.xaf: return 'FCFA';
      case CurrencyCode.xcd: return 'EC\$';
      case CurrencyCode.xof: return 'CFA';
      case CurrencyCode.xpf: return '₣';
      case CurrencyCode.yer: return 'YR';
      case CurrencyCode.zar: return 'R';
      case CurrencyCode.zmw: return 'ZK';
      case CurrencyCode.zwl: return 'Z\$';
    }
  }

  /// English display name
  String get displayName {
    switch (this) {
      case CurrencyCode.aed: return 'United Arab Emirates Dirham';
      case CurrencyCode.afn: return 'Afghan Afghani';
      case CurrencyCode.all: return 'Albanian Lek';
      case CurrencyCode.amd: return 'Armenian Dram';
      case CurrencyCode.ang: return 'Netherlands Antillean Guilder';
      case CurrencyCode.aoa: return 'Angolan Kwanza';
      case CurrencyCode.ars: return 'Argentine Peso';
      case CurrencyCode.aud: return 'Australian Dollar';
      case CurrencyCode.awg: return 'Aruban Florin';
      case CurrencyCode.azn: return 'Azerbaijani Manat';
      case CurrencyCode.bam: return 'Bosnia-Herzegovina Convertible Mark';
      case CurrencyCode.bbd: return 'Barbadian Dollar';
      case CurrencyCode.bdt: return 'Bangladeshi Taka';
      case CurrencyCode.bgn: return 'Bulgarian Lev';
      case CurrencyCode.bhd: return 'Bahraini Dinar';
      case CurrencyCode.bif: return 'Burundian Franc';
      case CurrencyCode.bmd: return 'Bermudan Dollar';
      case CurrencyCode.bnd: return 'Brunei Dollar';
      case CurrencyCode.bob: return 'Bolivian Boliviano';
      case CurrencyCode.brl: return 'Brazilian Real';
      case CurrencyCode.bsd: return 'Bahamian Dollar';
      case CurrencyCode.btn: return 'Bhutanese Ngultrum';
      case CurrencyCode.bwp: return 'Botswanan Pula';
      case CurrencyCode.byn: return 'Belarusian Ruble';
      case CurrencyCode.bzd: return 'Belize Dollar';
      case CurrencyCode.cad: return 'Canadian Dollar';
      case CurrencyCode.cdf: return 'Congolese Franc';
      case CurrencyCode.chf: return 'Swiss Franc';
      case CurrencyCode.clp: return 'Chilean Peso';
      case CurrencyCode.cny: return 'Chinese Yuan';
      case CurrencyCode.cop: return 'Colombian Peso';
      case CurrencyCode.crc: return 'Costa Rican Colón';
      case CurrencyCode.cup: return 'Cuban Peso';
      case CurrencyCode.cve: return 'Cape Verdean Escudo';
      case CurrencyCode.czk: return 'Czech Koruna';
      case CurrencyCode.djf: return 'Djiboutian Franc';
      case CurrencyCode.dkk: return 'Danish Krone';
      case CurrencyCode.dop: return 'Dominican Peso';
      case CurrencyCode.dzd: return 'Algerian Dinar';
      case CurrencyCode.egp: return 'Egyptian Pound';
      case CurrencyCode.ern: return 'Eritrean Nakfa';
      case CurrencyCode.etb: return 'Ethiopian Birr';
      case CurrencyCode.eur: return 'Euro';
      case CurrencyCode.fjd: return 'Fijian Dollar';
      case CurrencyCode.fkp: return 'Falkland Islands Pound';
      case CurrencyCode.gbp: return 'British Pound Sterling';
      case CurrencyCode.gel: return 'Georgian Lari';
      case CurrencyCode.ghs: return 'Ghanaian Cedi';
      case CurrencyCode.gip: return 'Gibraltar Pound';
      case CurrencyCode.gmd: return 'Gambian Dalasi';
      case CurrencyCode.gnf: return 'Guinean Franc';
      case CurrencyCode.gtq: return 'Guatemalan Quetzal';
      case CurrencyCode.gyd: return 'Guyanaese Dollar';
      case CurrencyCode.hkd: return 'Hong Kong Dollar';
      case CurrencyCode.hnl: return 'Honduran Lempira';
      case CurrencyCode.hrk: return 'Croatian Kuna';
      case CurrencyCode.htg: return 'Haitian Gourde';
      case CurrencyCode.huf: return 'Hungarian Forint';
      case CurrencyCode.idr: return 'Indonesian Rupiah';
      case CurrencyCode.ils: return 'Israeli New Shekel';
      case CurrencyCode.inr: return 'Indian Rupee';
      case CurrencyCode.iqd: return 'Iraqi Dinar';
      case CurrencyCode.irr: return 'Iranian Rial';
      case CurrencyCode.isk: return 'Icelandic Króna';
      case CurrencyCode.jmd: return 'Jamaican Dollar';
      case CurrencyCode.jod: return 'Jordanian Dinar';
      case CurrencyCode.jpy: return 'Japanese Yen';
      case CurrencyCode.kes: return 'Kenyan Shilling';
      case CurrencyCode.kgs: return 'Kyrgystani Som';
      case CurrencyCode.khr: return 'Cambodian Riel';
      case CurrencyCode.kmf: return 'Comorian Franc';
      case CurrencyCode.kpw: return 'North Korean Won';
      case CurrencyCode.krw: return 'South Korean Won';
      case CurrencyCode.kwd: return 'Kuwaiti Dinar';
      case CurrencyCode.kyd: return 'Cayman Islands Dollar';
      case CurrencyCode.kzt: return 'Kazakhstani Tenge';
      case CurrencyCode.lak: return 'Laotian Kip';
      case CurrencyCode.lbp: return 'Lebanese Pound';
      case CurrencyCode.lkr: return 'Sri Lankan Rupee';
      case CurrencyCode.lrd: return 'Liberian Dollar';
      case CurrencyCode.lsl: return 'Lesotho Loti';
      case CurrencyCode.lyd: return 'Libyan Dinar';
      case CurrencyCode.mad: return 'Moroccan Dirham';
      case CurrencyCode.mdl: return 'Moldovan Leu';
      case CurrencyCode.mga: return 'Malagasy Ariary';
      case CurrencyCode.mkd: return 'Macedonian Denar';
      case CurrencyCode.mmk: return 'Myanmar Kyat';
      case CurrencyCode.mnt: return 'Mongolian Tugrik';
      case CurrencyCode.mop: return 'Macanese Pataca';
      case CurrencyCode.mru: return 'Mauritanian Ouguiya';
      case CurrencyCode.mur: return 'Mauritian Rupee';
      case CurrencyCode.mvr: return 'Maldivian Rufiyaa';
      case CurrencyCode.mwk: return 'Malawian Kwacha';
      case CurrencyCode.mxn: return 'Mexican Peso';
      case CurrencyCode.myr: return 'Malaysian Ringgit';
      case CurrencyCode.mzn: return 'Mozambican Metical';
      case CurrencyCode.nad: return 'Namibian Dollar';
      case CurrencyCode.ngn: return 'Nigerian Naira';
      case CurrencyCode.nio: return 'Nicaraguan Córdoba';
      case CurrencyCode.nok: return 'Norwegian Krone';
      case CurrencyCode.npr: return 'Nepalese Rupee';
      case CurrencyCode.nzd: return 'New Zealand Dollar';
      case CurrencyCode.omr: return 'Omani Rial';
      case CurrencyCode.pab: return 'Panamanian Balboa';
      case CurrencyCode.pen: return 'Peruvian Nuevo Sol';
      case CurrencyCode.pgk: return 'Papua New Guinean Kina';
      case CurrencyCode.php: return 'Philippine Peso';
      case CurrencyCode.pkr: return 'Pakistani Rupee';
      case CurrencyCode.pln: return 'Polish Zloty';
      case CurrencyCode.pyg: return 'Paraguayan Guarani';
      case CurrencyCode.qar: return 'Qatari Rial';
      case CurrencyCode.ron: return 'Romanian Leu';
      case CurrencyCode.rsd: return 'Serbian Dinar';
      case CurrencyCode.rub: return 'Russian Ruble';
      case CurrencyCode.rwf: return 'Rwandan Franc';
      case CurrencyCode.sar: return 'Saudi Riyal';
      case CurrencyCode.sbd: return 'Solomon Islands Dollar';
      case CurrencyCode.scr: return 'Seychellois Rupee';
      case CurrencyCode.sdg: return 'Sudanese Pound';
      case CurrencyCode.sek: return 'Swedish Krona';
      case CurrencyCode.sgd: return 'Singapore Dollar';
      case CurrencyCode.shp: return 'Saint Helena Pound';
      case CurrencyCode.sll: return 'Sierra Leonean Leone';
      case CurrencyCode.sos: return 'Somali Shilling';
      case CurrencyCode.srd: return 'Surinamese Dollar';
      case CurrencyCode.ssp: return 'South Sudanese Pound';
      case CurrencyCode.stn: return 'São Tomé and Príncipe Dobra';
      case CurrencyCode.syp: return 'Syrian Pound';
      case CurrencyCode.szl: return 'Swazi Lilangeni';
      case CurrencyCode.thb: return 'Thai Baht';
      case CurrencyCode.tjs: return 'Tajikistani Somoni';
      case CurrencyCode.tmt: return 'Turkmenistani Manat';
      case CurrencyCode.tnd: return 'Tunisian Dinar';
      case CurrencyCode.top: return 'Tongan Paʻanga';
      case CurrencyCode.try: return 'Turkish Lira';
      case CurrencyCode.ttd: return 'Trinidad and Tobago Dollar';
      case CurrencyCode.twd: return 'New Taiwan Dollar';
      case CurrencyCode.tzs: return 'Tanzanian Shilling';
      case CurrencyCode.uah: return 'Ukrainian Hryvnia';
      case CurrencyCode.ugx: return 'Ugandan Shilling';
      case CurrencyCode.usd: return 'United States Dollar';
      case CurrencyCode.uyu: return 'Uruguayan Peso';
      case CurrencyCode.uzs: return 'Uzbekistan Som';
      case CurrencyCode.ves: return 'Venezuelan Bolívar';
      case CurrencyCode.vnd: return 'Vietnamese Dong';
      case CurrencyCode.vuv: return 'Vanuatu Vatu';
      case CurrencyCode.wst: return 'Samoan Tala';
      case CurrencyCode.xaf: return 'Central African CFA Franc';
      case CurrencyCode.xcd: return 'East Caribbean Dollar';
      case CurrencyCode.xof: return 'West African CFA Franc';
      case CurrencyCode.xpf: return 'CFP Franc';
      case CurrencyCode.yer: return 'Yemeni Rial';
      case CurrencyCode.zar: return 'South African Rand';
      case CurrencyCode.zmw: return 'Zambian Kwacha';
      case CurrencyCode.zwl: return 'Zimbabwean Dollar';
    }
  }

  /// Whether currency is actively used
  bool get isActive {
    switch (this) {
      case CurrencyCode.aed:
      case CurrencyCode.afn:
      case CurrencyCode.all:
      case CurrencyCode.amd:
      case CurrencyCode.ang:
      case CurrencyCode.aoa:
      case CurrencyCode.ars:
      case CurrencyCode.aud:
      case CurrencyCode.awg:
      case CurrencyCode.azn:
      case CurrencyCode.bam:
      case CurrencyCode.bbd:
      case CurrencyCode.bdt:
      case CurrencyCode.bgn:
      case CurrencyCode.bhd:
      case CurrencyCode.bif:
      case CurrencyCode.bmd:
      case CurrencyCode.bnd:
      case CurrencyCode.bob:
      case CurrencyCode.brl:
      case CurrencyCode.bsd:
      case CurrencyCode.btn:
      case CurrencyCode.bwp:
      case CurrencyCode.byn:
      case CurrencyCode.bzd:
      case CurrencyCode.cad:
      case CurrencyCode.cdf:
      case CurrencyCode.chf:
      case CurrencyCode.clp:
      case CurrencyCode.cny:
      case CurrencyCode.cop:
      case CurrencyCode.crc:
      case CurrencyCode.cup:
      case CurrencyCode.cve:
      case CurrencyCode.czk:
      case CurrencyCode.djf:
      case CurrencyCode.dkk:
      case CurrencyCode.dop:
      case CurrencyCode.dzd:
      case CurrencyCode.egp:
      case CurrencyCode.ern:
      case CurrencyCode.etb:
      case CurrencyCode.eur:
      case CurrencyCode.fjd:
      case CurrencyCode.fkp:
      case CurrencyCode.gbp:
      case CurrencyCode.gel:
      case CurrencyCode.ghs:
      case CurrencyCode.gip:
      case CurrencyCode.gmd:
      case CurrencyCode.gnf:
      case CurrencyCode.gtq:
      case CurrencyCode.gyd:
      case CurrencyCode.hkd:
      case CurrencyCode.hnl:
      case CurrencyCode.htg:
      case CurrencyCode.huf:
      case CurrencyCode.idr:
      case CurrencyCode.ils:
      case CurrencyCode.inr:
      case CurrencyCode.iqd:
      case CurrencyCode.irr:
      case CurrencyCode.isk:
      case CurrencyCode.jmd:
      case CurrencyCode.jod:
      case CurrencyCode.jpy:
      case CurrencyCode.kes:
      case CurrencyCode.kgs:
      case CurrencyCode.khr:
      case CurrencyCode.kmf:
      case CurrencyCode.kpw:
      case CurrencyCode.krw:
      case CurrencyCode.kwd:
      case CurrencyCode.kyd:
      case CurrencyCode.kzt:
      case CurrencyCode.lak:
      case CurrencyCode.lbp:
      case CurrencyCode.lkr:
      case CurrencyCode.lrd:
      case CurrencyCode.lsl:
      case CurrencyCode.lyd:
      case CurrencyCode.mad:
      case CurrencyCode.mdl:
      case CurrencyCode.mga:
      case CurrencyCode.mkd:
      case CurrencyCode.mmk:
      case CurrencyCode.mnt:
      case CurrencyCode.mop:
      case CurrencyCode.mru:
      case CurrencyCode.mur:
      case CurrencyCode.mvr:
      case CurrencyCode.mwk:
      case CurrencyCode.mxn:
      case CurrencyCode.myr:
      case CurrencyCode.mzn:
      case CurrencyCode.nad:
      case CurrencyCode.ngn:
      case CurrencyCode.nio:
      case CurrencyCode.nok:
      case CurrencyCode.npr:
      case CurrencyCode.nzd:
      case CurrencyCode.omr:
      case CurrencyCode.pab:
      case CurrencyCode.pen:
      case CurrencyCode.pgk:
      case CurrencyCode.php:
      case CurrencyCode.pkr:
      case CurrencyCode.pln:
      case CurrencyCode.pyg:
      case CurrencyCode.qar:
      case CurrencyCode.ron:
      case CurrencyCode.rsd:
      case CurrencyCode.rub:
      case CurrencyCode.rwf:
      case CurrencyCode.sar:
      case CurrencyCode.sbd:
      case CurrencyCode.scr:
      case CurrencyCode.sdg:
      case CurrencyCode.sek:
      case CurrencyCode.sgd:
      case CurrencyCode.shp:
      case CurrencyCode.sll:
      case CurrencyCode.sos:
      case CurrencyCode.srd:
      case CurrencyCode.ssp:
      case CurrencyCode.stn:
      case CurrencyCode.syp:
      case CurrencyCode.szl:
      case CurrencyCode.thb:
      case CurrencyCode.tjs:
      case CurrencyCode.tmt:
      case CurrencyCode.tnd:
      case CurrencyCode.top:
      case CurrencyCode.try:
      case CurrencyCode.ttd:
      case CurrencyCode.twd:
      case CurrencyCode.tzs:
      case CurrencyCode.uah:
      case CurrencyCode.ugx:
      case CurrencyCode.usd:
      case CurrencyCode.uyu:
      case CurrencyCode.uzs:
      case CurrencyCode.ves:
      case CurrencyCode.vnd:
      case CurrencyCode.vuv:
      case CurrencyCode.wst:
      case CurrencyCode.xaf:
      case CurrencyCode.xcd:
      case CurrencyCode.xof:
      case CurrencyCode.xpf:
      case CurrencyCode.yer:
      case CurrencyCode.zar:
      case CurrencyCode.zmw:
      case CurrencyCode.zwl:
        return true;
      case CurrencyCode.hrk:
        return false;
    }
  }
}
