name: Auto Version Bump

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'pubspec.yaml'
      - '.github/workflows/version-bump.yml'

permissions:
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump patch version
        run: |
          chmod +x .github/scripts/bump-version.sh
          .github/scripts/bump-version.sh

      - name: Commit and push version bump
        run: |
          git add pubspec.yaml
          if [ -f "lib/core/config/app_config.dart" ]; then
            git add lib/core/config/app_config.dart
          fi

          NEW_VERSION=$(grep "^version:" pubspec.yaml | sed 's/version: //')
          git commit -m "chore: bump version to $NEW_VERSION [skip ci]" || echo "No changes to commit"
          git push origin master || echo "Nothing to push"
