// Mocks generated by Mockito 5.4.6 from annotations
// in expense_tracker/test/features/settlements/presentation/cubits/settlement_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:expense_tracker/core/services/local_storage_service.dart'
    as _i14;
import 'package:expense_tracker/features/categories/domain/models/category.dart'
    as _i5;
import 'package:expense_tracker/features/categories/domain/repositories/category_repository.dart'
    as _i13;
import 'package:expense_tracker/features/expenses/domain/models/expense.dart'
    as _i3;
import 'package:expense_tracker/features/expenses/domain/repositories/expense_repository.dart'
    as _i9;
import 'package:expense_tracker/features/settlements/domain/models/minimal_transfer.dart'
    as _i8;
import 'package:expense_tracker/features/settlements/domain/models/settlement_summary.dart'
    as _i2;
import 'package:expense_tracker/features/settlements/domain/repositories/settled_transfer_repository.dart'
    as _i12;
import 'package:expense_tracker/features/settlements/domain/repositories/settlement_repository.dart'
    as _i6;
import 'package:expense_tracker/features/trips/domain/models/trip.dart' as _i4;
import 'package:expense_tracker/features/trips/domain/models/verified_member.dart'
    as _i11;
import 'package:expense_tracker/features/trips/domain/repositories/trip_repository.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSettlementSummary_0 extends _i1.SmartFake
    implements _i2.SettlementSummary {
  _FakeSettlementSummary_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExpense_1 extends _i1.SmartFake implements _i3.Expense {
  _FakeExpense_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTrip_2 extends _i1.SmartFake implements _i4.Trip {
  _FakeTrip_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategory_3 extends _i1.SmartFake implements _i5.Category {
  _FakeCategory_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SettlementRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettlementRepository extends _i1.Mock
    implements _i6.SettlementRepository {
  @override
  _i7.Future<_i2.SettlementSummary?> getSettlementSummary(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#getSettlementSummary, [tripId]),
            returnValue: _i7.Future<_i2.SettlementSummary?>.value(),
            returnValueForMissingStub:
                _i7.Future<_i2.SettlementSummary?>.value(),
          )
          as _i7.Future<_i2.SettlementSummary?>);

  @override
  _i7.Stream<_i2.SettlementSummary?> watchSettlementSummary(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#watchSettlementSummary, [tripId]),
            returnValue: _i7.Stream<_i2.SettlementSummary?>.empty(),
            returnValueForMissingStub:
                _i7.Stream<_i2.SettlementSummary?>.empty(),
          )
          as _i7.Stream<_i2.SettlementSummary?>);

  @override
  _i7.Stream<List<_i8.MinimalTransfer>> getMinimalTransfers(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#getMinimalTransfers, [tripId]),
            returnValue: _i7.Stream<List<_i8.MinimalTransfer>>.empty(),
            returnValueForMissingStub:
                _i7.Stream<List<_i8.MinimalTransfer>>.empty(),
          )
          as _i7.Stream<List<_i8.MinimalTransfer>>);

  @override
  _i7.Future<_i2.SettlementSummary> computeSettlement(
    String? tripId, {
    dynamic currencyFilter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #computeSettlement,
              [tripId],
              {#currencyFilter: currencyFilter},
            ),
            returnValue: _i7.Future<_i2.SettlementSummary>.value(
              _FakeSettlementSummary_0(
                this,
                Invocation.method(
                  #computeSettlement,
                  [tripId],
                  {#currencyFilter: currencyFilter},
                ),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i2.SettlementSummary>.value(
              _FakeSettlementSummary_0(
                this,
                Invocation.method(
                  #computeSettlement,
                  [tripId],
                  {#currencyFilter: currencyFilter},
                ),
              ),
            ),
          )
          as _i7.Future<_i2.SettlementSummary>);

  @override
  _i7.Future<_i2.SettlementSummary> computeSettlementWithExpenses(
    String? tripId,
    List<_i3.Expense>? expenses, {
    dynamic currencyFilter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #computeSettlementWithExpenses,
              [tripId, expenses],
              {#currencyFilter: currencyFilter},
            ),
            returnValue: _i7.Future<_i2.SettlementSummary>.value(
              _FakeSettlementSummary_0(
                this,
                Invocation.method(
                  #computeSettlementWithExpenses,
                  [tripId, expenses],
                  {#currencyFilter: currencyFilter},
                ),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i2.SettlementSummary>.value(
              _FakeSettlementSummary_0(
                this,
                Invocation.method(
                  #computeSettlementWithExpenses,
                  [tripId, expenses],
                  {#currencyFilter: currencyFilter},
                ),
              ),
            ),
          )
          as _i7.Future<_i2.SettlementSummary>);

  @override
  _i7.Future<bool> settlementExists(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#settlementExists, [tripId]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> deleteSettlement(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSettlement, [tripId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> markTransferAsSettled(String? tripId, String? transferId) =>
      (super.noSuchMethod(
            Invocation.method(#markTransferAsSettled, [tripId, transferId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> shouldRecompute(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#shouldRecompute, [tripId]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);
}

/// A class which mocks [ExpenseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpenseRepository extends _i1.Mock implements _i9.ExpenseRepository {
  @override
  _i7.Future<_i3.Expense> createExpense(_i3.Expense? expense) =>
      (super.noSuchMethod(
            Invocation.method(#createExpense, [expense]),
            returnValue: _i7.Future<_i3.Expense>.value(
              _FakeExpense_1(
                this,
                Invocation.method(#createExpense, [expense]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i3.Expense>.value(
              _FakeExpense_1(
                this,
                Invocation.method(#createExpense, [expense]),
              ),
            ),
          )
          as _i7.Future<_i3.Expense>);

  @override
  _i7.Future<_i3.Expense?> getExpenseById(String? expenseId) =>
      (super.noSuchMethod(
            Invocation.method(#getExpenseById, [expenseId]),
            returnValue: _i7.Future<_i3.Expense?>.value(),
            returnValueForMissingStub: _i7.Future<_i3.Expense?>.value(),
          )
          as _i7.Future<_i3.Expense?>);

  @override
  _i7.Stream<List<_i3.Expense>> getExpensesByTrip(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#getExpensesByTrip, [tripId]),
            returnValue: _i7.Stream<List<_i3.Expense>>.empty(),
            returnValueForMissingStub: _i7.Stream<List<_i3.Expense>>.empty(),
          )
          as _i7.Stream<List<_i3.Expense>>);

  @override
  _i7.Future<_i3.Expense> updateExpense(_i3.Expense? expense) =>
      (super.noSuchMethod(
            Invocation.method(#updateExpense, [expense]),
            returnValue: _i7.Future<_i3.Expense>.value(
              _FakeExpense_1(
                this,
                Invocation.method(#updateExpense, [expense]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i3.Expense>.value(
              _FakeExpense_1(
                this,
                Invocation.method(#updateExpense, [expense]),
              ),
            ),
          )
          as _i7.Future<_i3.Expense>);

  @override
  _i7.Future<void> deleteExpense(String? expenseId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteExpense, [expenseId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> expenseExists(String? expenseId) =>
      (super.noSuchMethod(
            Invocation.method(#expenseExists, [expenseId]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Stream<List<_i3.Expense>> getExpensesByCategory(
    String? tripId,
    String? categoryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExpensesByCategory, [tripId, categoryId]),
            returnValue: _i7.Stream<List<_i3.Expense>>.empty(),
            returnValueForMissingStub: _i7.Stream<List<_i3.Expense>>.empty(),
          )
          as _i7.Stream<List<_i3.Expense>>);

  @override
  _i7.Stream<List<_i3.Expense>> getExpensesByPayer(
    String? tripId,
    String? payerUserId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExpensesByPayer, [tripId, payerUserId]),
            returnValue: _i7.Stream<List<_i3.Expense>>.empty(),
            returnValueForMissingStub: _i7.Stream<List<_i3.Expense>>.empty(),
          )
          as _i7.Stream<List<_i3.Expense>>);
}

/// A class which mocks [TripRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTripRepository extends _i1.Mock implements _i10.TripRepository {
  @override
  _i7.Future<_i4.Trip> createTrip(_i4.Trip? trip) =>
      (super.noSuchMethod(
            Invocation.method(#createTrip, [trip]),
            returnValue: _i7.Future<_i4.Trip>.value(
              _FakeTrip_2(this, Invocation.method(#createTrip, [trip])),
            ),
            returnValueForMissingStub: _i7.Future<_i4.Trip>.value(
              _FakeTrip_2(this, Invocation.method(#createTrip, [trip])),
            ),
          )
          as _i7.Future<_i4.Trip>);

  @override
  _i7.Future<_i4.Trip?> getTripById(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#getTripById, [tripId]),
            returnValue: _i7.Future<_i4.Trip?>.value(),
            returnValueForMissingStub: _i7.Future<_i4.Trip?>.value(),
          )
          as _i7.Future<_i4.Trip?>);

  @override
  _i7.Stream<List<_i4.Trip>> getAllTrips() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTrips, []),
            returnValue: _i7.Stream<List<_i4.Trip>>.empty(),
            returnValueForMissingStub: _i7.Stream<List<_i4.Trip>>.empty(),
          )
          as _i7.Stream<List<_i4.Trip>>);

  @override
  _i7.Future<_i4.Trip> updateTrip(_i4.Trip? trip) =>
      (super.noSuchMethod(
            Invocation.method(#updateTrip, [trip]),
            returnValue: _i7.Future<_i4.Trip>.value(
              _FakeTrip_2(this, Invocation.method(#updateTrip, [trip])),
            ),
            returnValueForMissingStub: _i7.Future<_i4.Trip>.value(
              _FakeTrip_2(this, Invocation.method(#updateTrip, [trip])),
            ),
          )
          as _i7.Future<_i4.Trip>);

  @override
  _i7.Future<void> deleteTrip(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTrip, [tripId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> tripExists(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#tripExists, [tripId]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> addVerifiedMember({
    required String? tripId,
    required String? participantId,
    required String? participantName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addVerifiedMember, [], {
              #tripId: tripId,
              #participantId: participantId,
              #participantName: participantName,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i11.VerifiedMember>> getVerifiedMembers(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#getVerifiedMembers, [tripId]),
            returnValue: _i7.Future<List<_i11.VerifiedMember>>.value(
              <_i11.VerifiedMember>[],
            ),
            returnValueForMissingStub:
                _i7.Future<List<_i11.VerifiedMember>>.value(
                  <_i11.VerifiedMember>[],
                ),
          )
          as _i7.Future<List<_i11.VerifiedMember>>);

  @override
  _i7.Future<void> removeVerifiedMember({
    required String? tripId,
    required String? participantId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeVerifiedMember, [], {
              #tripId: tripId,
              #participantId: participantId,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<dynamic>> getAllowedCurrencies(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#getAllowedCurrencies, [tripId]),
            returnValue: _i7.Future<List<dynamic>>.value(<dynamic>[]),
            returnValueForMissingStub: _i7.Future<List<dynamic>>.value(
              <dynamic>[],
            ),
          )
          as _i7.Future<List<dynamic>>);

  @override
  _i7.Future<void> updateAllowedCurrencies(
    String? tripId,
    List<dynamic>? currencies,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAllowedCurrencies, [tripId, currencies]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [SettledTransferRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettledTransferRepository extends _i1.Mock
    implements _i12.SettledTransferRepository {
  @override
  _i7.Stream<List<_i8.MinimalTransfer>> getSettledTransfers(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#getSettledTransfers, [tripId]),
            returnValue: _i7.Stream<List<_i8.MinimalTransfer>>.empty(),
            returnValueForMissingStub:
                _i7.Stream<List<_i8.MinimalTransfer>>.empty(),
          )
          as _i7.Stream<List<_i8.MinimalTransfer>>);

  @override
  _i7.Future<void> markTransferAsSettled(
    String? tripId,
    String? fromUserId,
    String? toUserId,
    String? amountBase,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markTransferAsSettled, [
              tripId,
              fromUserId,
              toUserId,
              amountBase,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> unmarkTransferAsSettled(
    String? tripId,
    String? transferId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#unmarkTransferAsSettled, [tripId, transferId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteSettledTransfersForTrip(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSettledTransfersForTrip, [tripId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i13.CategoryRepository {
  @override
  _i7.Stream<List<_i5.Category>> getTopCategories({int? limit = 5}) =>
      (super.noSuchMethod(
            Invocation.method(#getTopCategories, [], {#limit: limit}),
            returnValue: _i7.Stream<List<_i5.Category>>.empty(),
            returnValueForMissingStub: _i7.Stream<List<_i5.Category>>.empty(),
          )
          as _i7.Stream<List<_i5.Category>>);

  @override
  _i7.Stream<List<_i5.Category>> searchCategories(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchCategories, [query]),
            returnValue: _i7.Stream<List<_i5.Category>>.empty(),
            returnValueForMissingStub: _i7.Stream<List<_i5.Category>>.empty(),
          )
          as _i7.Stream<List<_i5.Category>>);

  @override
  _i7.Future<_i5.Category?> getCategoryById(String? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#getCategoryById, [categoryId]),
            returnValue: _i7.Future<_i5.Category?>.value(),
            returnValueForMissingStub: _i7.Future<_i5.Category?>.value(),
          )
          as _i7.Future<_i5.Category?>);

  @override
  _i7.Future<List<_i5.Category>> getCategoriesByIds(List<String>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#getCategoriesByIds, [ids]),
            returnValue: _i7.Future<List<_i5.Category>>.value(<_i5.Category>[]),
            returnValueForMissingStub: _i7.Future<List<_i5.Category>>.value(
              <_i5.Category>[],
            ),
          )
          as _i7.Future<List<_i5.Category>>);

  @override
  _i7.Future<_i5.Category> createCategory({
    required String? name,
    String? icon = 'label',
    required String? color,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createCategory, [], {
              #name: name,
              #icon: icon,
              #color: color,
              #userId: userId,
            }),
            returnValue: _i7.Future<_i5.Category>.value(
              _FakeCategory_3(
                this,
                Invocation.method(#createCategory, [], {
                  #name: name,
                  #icon: icon,
                  #color: color,
                  #userId: userId,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i5.Category>.value(
              _FakeCategory_3(
                this,
                Invocation.method(#createCategory, [], {
                  #name: name,
                  #icon: icon,
                  #color: color,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i7.Future<_i5.Category>);

  @override
  _i7.Future<void> incrementCategoryUsage(String? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#incrementCategoryUsage, [categoryId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> categoryExists(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#categoryExists, [name]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> canUserCreateCategory(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#canUserCreateCategory, [userId]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<List<_i5.Category>> seedDefaultCategories() =>
      (super.noSuchMethod(
            Invocation.method(#seedDefaultCategories, []),
            returnValue: _i7.Future<List<_i5.Category>>.value(<_i5.Category>[]),
            returnValueForMissingStub: _i7.Future<List<_i5.Category>>.value(
              <_i5.Category>[],
            ),
          )
          as _i7.Future<List<_i5.Category>>);

  @override
  _i7.Future<List<_i13.SimilarCategoryMatch>> findSimilarCategories(
    String? query, {
    double? threshold = 0.8,
    int? limit = 3,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #findSimilarCategories,
              [query],
              {#threshold: threshold, #limit: limit},
            ),
            returnValue: _i7.Future<List<_i13.SimilarCategoryMatch>>.value(
              <_i13.SimilarCategoryMatch>[],
            ),
            returnValueForMissingStub:
                _i7.Future<List<_i13.SimilarCategoryMatch>>.value(
                  <_i13.SimilarCategoryMatch>[],
                ),
          )
          as _i7.Future<List<_i13.SimilarCategoryMatch>>);

  @override
  _i7.Future<String?> getMostPopularIcon(String? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#getMostPopularIcon, [categoryId]),
            returnValue: _i7.Future<String?>.value(),
            returnValueForMissingStub: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);
}

/// A class which mocks [LocalStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageService extends _i1.Mock
    implements _i14.LocalStorageService {
  @override
  _i7.Future<void> saveSelectedTripId(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#saveSelectedTripId, [tripId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> clearSelectedTripId() =>
      (super.noSuchMethod(
            Invocation.method(#clearSelectedTripId, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> addJoinedTrip(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#addJoinedTrip, [tripId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  bool verifyJoinedTrip(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#verifyJoinedTrip, [tripId]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<String> getJoinedTripIds() =>
      (super.noSuchMethod(
            Invocation.method(#getJoinedTripIds, []),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  _i7.Future<void> removeJoinedTrip(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#removeJoinedTrip, [tripId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> saveUserIdentityForTrip(
    String? tripId,
    String? participantId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserIdentityForTrip, [
              tripId,
              participantId,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  String? getUserIdentityForTrip(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserIdentityForTrip, [tripId]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  _i7.Future<void> removeUserIdentityForTrip(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#removeUserIdentityForTrip, [tripId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> clearAllUserIdentities() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllUserIdentities, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> saveSettlementFilter(
    String? tripId, {
    String? userId,
    String? filterMode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #saveSettlementFilter,
              [tripId],
              {#userId: userId, #filterMode: filterMode},
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  ({String filterMode, String? userId}) getSettlementFilter(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#getSettlementFilter, [tripId]),
            returnValue: (
              filterMode: _i15.dummyValue<String>(
                this,
                Invocation.method(#getSettlementFilter, [tripId]),
              ),
              userId: null,
            ),
            returnValueForMissingStub: (
              filterMode: _i15.dummyValue<String>(
                this,
                Invocation.method(#getSettlementFilter, [tripId]),
              ),
              userId: null,
            ),
          )
          as ({String filterMode, String? userId}));

  @override
  _i7.Future<void> clearSettlementFilter(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#clearSettlementFilter, [tripId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
